In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0]

0

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr =np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[:5]


In [14]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [15]:
slice_of_arr[:] = 99

In [16]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr = np.arange(0,5,1)

In [18]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [19]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [20]:
arr_copy = arr.copy()

In [21]:
arr_copy[:] = 100

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [24]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d_test = np.linspace(5,45,9)

In [27]:
arr_2d_test

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [28]:
arr_2d_test.reshape(3,3)

array([[ 5., 10., 15.],
       [20., 25., 30.],
       [35., 40., 45.]])

In [30]:
type(arr_2d_test)

numpy.ndarray

In [31]:
type(arr_2d_test[0])

numpy.float64

In [34]:
arr_2d_test = arr_2d_test.reshape(3,3)

In [35]:
arr_2d_test[0,2]

15.0

In [37]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [38]:
arr = np.arange(1,11)

In [39]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
np.arange(5,45,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40])

In [41]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [42]:
bool_arr = arr>4

In [43]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])